name: ArenaManager
version: '${version}'
main: pl.nadwey.arenamanager.ArenaManager
api-version: '1.20'
softdepend: [BlueSlimeCore]

permissions:
  arenamanager.command.arenas:
    description: "Access to the '/arenas' command."
    default: true
  arenamanager.command.arena:
    description: "Access to the '/arena' command."
    default: op
  arenamanager.command.arena.create:
    description: "Access to the '/arena create' command."
    default: op
  arenamanager.command.arena.displayName:
    description: "Access to the '/arena displayName' command."
    default: op
