name: NadArenas
version: '${version}'
main: pl.nadwey.nadarenas.NadArenas
api-version: '1.20'

permissions:
  nadarenas.command.arenas:
    description: "Access to the '/arenas' command."
    default: true
  nadarenas.command.nadarenas:
    description: "Access to the '/nadarenas' command."
    default: op
  nadarenas.command.nadarenas.arena.create:
    description: "Access to the '/nadarenas create arena' command."
    default: op
  nadarenas.command.nadarenas.arena.list:
      description: "Access to the '/nadarenas arena list' command."
      default: op
  nadarenas.command.nadarenas.arena.displayname:
    description: "Access to the '/nadarenas arena displayName' command."
    default: op
  nadarenas.command.nadarenas.arena.remove:
    description: "Access to the '/nadarenas arena remove' command."
    default: op
  nadarenas.command.nadarenas.arena.description:
    description: "Access to the '/nadarenas arena description' command."
    default: op
  nadarenas.command.nadarenas.arena.item:
    description: "Access to the '/nadarenas arena item' command."
    default: op
  nadarenas.command.nadarenas.arena.load:
    description: "Access to the '/nadarenas arena load' command."
    default: op