name: NadArenas
version: '${version}'
main: pl.nadwey.nadarenas.NadArenas
api-version: '1.20'

permissions:
  nadarenas.command.arenas:
    description: "Access to the '/arenas' command."
    default: true
  nadarenas.command.nadarenas:
    description: "Access to the '/nadarenas' command."
    default: op
  nadarenas.command.nadarenas.arena.create:
    description: "Access to the '/nadarenas create arena' command."
    default: op
  nadarenas.command.nadarenas.arena.list:
      description: "Access to the '/nadarenas arena list' command."
      default: op
  nadarenas.command.nadarenas.arena.setdisplayname:
    description: "Access to the '/nadarenas arena setDisplayName' command."
    default: op
  nadarenas.command.nadarenas.arena.remove:
    description: "Access to the '/nadarenas arena remove' command."
    default: op
  nadarenas.command.nadarenas.arena.setdescription:
    description: "Access to the '/nadarenas arena setDescription' command."
    default: op
  nadarenas.command.nadarenas.arena.setitem:
    description: "Access to the '/nadarenas arena setItem' command."
    default: op
  nadarenas.command.nadarenas.arena.loader:
    description: "Access to the '/nadarenas arena loader' command."
    default: op
  nadarenas.command.nadarenas.arena.loader.load:
    description: "Access to the '/nadarenas arena loader load' command."
    default: op
  nadarenas.command.nadarenas.arena.loader.setenabled:
    description: "Access to the '/nadarenas arena loader setEnabled' command."
    default: op
  nadarenas.command.nadarenas.arena.loader.setblockspertick:
    description: "Access to the '/nadarenas arena loader setBlocksPerTick' command."
    default: op
  nadarenas.command.reload:
    description: "Access to the '/nadarenas reload' command."
    default: op